name: my_flutter_app
description: "A new Flutter project."

publish_to: 'none' # Prevent accidental publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^5.0.0
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  provider: ^6.1.2
  shared_preferences: ^2.0.6


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1
  

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/login1.png
    - assets/logos.png
    - assets/logo.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logos.png"
  android_icon_scale: 5.0
